CREATE TABLE Person(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name varchar(100) NOT NULL UNIQUE,
    password varchar(100) NOT NULL
);

CREATE TABLE Cookie(
   id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   person_id int REFERENCES Person(id),
   entry_time TIMESTAMP WITH TIME ZONE,
   cookie_value varchar(100)
);

CREATE TABLE Note(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id int REFERENCES Person(id),
    time TIMESTAMP WITH TIME ZONE NOT NULL,
    note_text TEXT
);

DROP TABLE Person;
DROP TABLE Note;


SELECT * FROM pg_timezone_names;
SET timezone = 'Europe/Moscow';

INSERT INTO Person(user_name, password) VALUES ('balandox', 'balandox123');

INSERT INTO Note (user_id, time, note_text) VALUES
    (1, '2022-11-28 15:32:00', 'Сходить в магазин'),
    (1, (SELECT NOW()), 'Сходить в аптеку');


SELECT p.user_name, n.time, n.note_text FROM Person AS p
LEFT JOIN Note N on p.id = N.user_id;


SELECT p.user_name, c.entry_time, c.cookie_value FROM Person AS p
JOIN Cookie c on p.id = c.person_id;

SELECT * FROM Person